Update Postgres-Backup-and-Copy-to-S3-Bucket

diff --git a/Scripts/ShellScripts/Postgres-Backup-and-Copy-to-S3-Bucket b/Scripts/ShellScripts/Postgres-Backup-and-Copy-to-S3-Bucket
--- a/Scripts/ShellScripts/Postgres-Backup-and-Copy-to-S3-Bucket
+++ b/Scripts/ShellScripts/Postgres-Backup-and-Copy-to-S3-Bucket
@@ -1,39 +1,52 @@
 #!/bin/bash
 
-# Container name
-CONTAINER_NAME="db"
-
-# Container port
-CONTAINER_PORT=5432
-
-# Define database credentials
-DB_USER="dbuser"
-DB_PASSWORD="dbuserpassword"
-DB_NAME="db"
-BACKUP_DIR="/root/dbbackups"
-S3_BUCKET="s3://my-bucket/daily"
+# Variables
+DB_HOST=""
+DB_NAME=""
+DB_PORT=5432
+DB_USER=""
+DB_PASSWORD=""
+S3_BUCKET="s3://my-bucket/postgres/"
 
 # Generate timestamp
-TIMESTAMP=$(date +"%Y_%m_%d__%H_%M_%S")
+TIMESTAMP=$(date +"%Y_%m_%d__%H_%M_%S")  
+BACKUP_FILE="mainapp_${DB_NAME}_dbbackup_utc_${TIMESTAMP}.sql"
 
-# Define dump file name
-DUMP_FILE="dbbackup_${TIMESTAMP}.sql"
-DUMP_PATH="$BACKUP_DIR/$DUMP_FILE"
+# Set the PGPASSWORD environment variable for authentication
+export PGPASSWORD=$DB_PASSWORD
 
-# Execute pg_dump inside the container and save dump to a file, port on which db container is running
-docker exec -t $CONTAINER_NAME pg_dump -U $DB_USER -d $DB_NAME -p $CONTAINER_PORT > $DUMP_PATH
+# Perform the database backup and compress the output
+pg_dump -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" "$DB_NAME" > "$BACKUP_FILE"
 
-# Copy the dump file to an S3 bucket, aws cli should be configured and the user shouldhave access to put object in the bucket
-aws s3 cp $DUMP_PATH $S3_BUCKET/$DUMP_FILE
+# Check if the backup was successful
+if [ $? -eq 0 ]; then
+    echo "Database backup successful: $BACKUP_FILE"
+else
+    echo "Database backup failed!" >&2
+    exit 1
+fi
 
-# RETENTION POLICY
-RETENTION_DAYS=7
-find $BACKUP_DIR -name "dbbackup_*.sql" -mtime +$RETENTION_DAYS -exec rm {} \;
+# Copy backup file to s3 bucket
+aws s3 cp "$BACKUP_FILE" "$S3_BUCKET"
 
-echo "Script Executed Successfully"
+# Check if the S3 upload was successful
+if [ $? -eq 0 ]; then
+    echo "Backup uploaded to S3: $S3_BUCKET"
+else
+    echo "Failed to upload backup to S3!" >&2
+    exit 1
+fi
 
+# Delete the local backup file to save space
+rm -f "$BACKUP_FILE"
 
-# RESTORING BACKUP IN LOCAL PGADMIN
-# 1. create a new database where you want to restore 
-# 2. right click on the database and open psql tool
-# 4. run this command -  \i '<BACKUP-PATH>'    example: \i 'E:/BACKUPS/<backupfilename>.sql'
+# Confirm deletion
+if [ $? -eq 0 ]; then
+    echo "Local backup file deleted & script execution complete."
+else
+    echo "Failed to delete local backup file!" >&2
+    exit 1
+fi
+
+# Unset the PGPASSWORD environment variable
+unset PGPASSWORD
